INSERT INTO usuario (id, username, password, admin) Values (1, '1', '{bcrypt}$2a$10$Uuis3306Cl3oU5Xv27zO9.Qll1s0xLuDMx3C/3rXMxPoDTXNN3q4i', false);
INSERT INTO usuario (id, username, password, admin) Values (2, '2', '{bcrypt}$2a$10$Uuis3306Cl3oU5Xv27zO9.Qll1s0xLuDMx3C/3rXMxPoDTXNN3q4i', false);
INSERT INTO usuario (id, username, password, admin) Values (999, 'admin', '{bcrypt}$2a$10$FvcsBE6b9i00wCH/Sbk1xeyQyY6/y1q5oEq6p18ZQXZ0L8v13kiI.', true);
INSERT INTO trabajador (id, apellido, email, nombre, precio_hora_extra, sueldo_base) Values (1, 'fanega', 'fanega@gmail.com','Alejandro' ,26, 3012);
INSERT INTO trabajador (id, apellido, email, nombre, precio_hora_extra, sueldo_base) Values (2, 'Claro', 'claro@gmail.com', 'José',29, 2312);
INSERT INTO cliente (id_cliente, apellido, ciudad, dni, email, nombre, telefono) Values (1, 'perez', 'madrid', '77654902F', 'perez@gmail.com', 'pepe', 675483297);
INSERT INTO cliente (id_cliente, apellido, ciudad, dni, email, nombre, telefono) Values (2, 'lópez', 'sevilla', '7797902S', 'lopez@gmail.com', 'paco', 675432873);
INSERT INTO reforma (id, fecha_final, fecha_inicio, presupuesto, calle, jefe_de_obra_id, propietario_id_cliente) Values (1, '2024-03-13', '2020-04-12', 12342, 'San Jacinto 96', 1, 1);
INSERT INTO reforma (id, fecha_final, fecha_inicio, presupuesto, calle, jefe_de_obra_id, propietario_id_cliente) Values (2, '2023-03-13', '2021-04-12', 12282, 'Pascual Marquez 124', 2, 1);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (1, 12, 'ladrillos', 16);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (2, 13, 'cemento', 17);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (3, 11, 'pintura', 19);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (4, 27, 'lámpara', 38);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (5, 15, 'espejo', 37);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (6, 69, 'váter', 93);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (7, 1, 'pvc', 3);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (8, 0.23, 'lijas', 1.2);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (9, 4.80, 'alfombrillas', 11.7);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (10, 135, 'plato de ducha', 398);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (11, 113.7, 'cableado', 209.7);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (12, 27, 'enchufes', 36);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (13, 14, 'iluminación', 28);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (14, 1798.34, 'aire acondicionado centralizado', 4007.14);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (15, 408.56, 'suelo', 713.57);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (16, 40, 'puertas', 100);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (17, 27, 'sillas', 76);
INSERT INTO materiales (id, coste, nombre, pvp_material) Values (18, 60, 'ventanas', 134);
INSERT INTO parte_trabajador (fecha, reforma_id, trabajador_id, num_horas, num_horas_extra) Values ('2023-04-10', 1, 1, 7, 2);
INSERT INTO parte_trabajador (fecha, reforma_id, trabajador_id, num_horas, num_horas_extra) Values ('2020-02-14', 2, 2, 4, 1);

ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART with 1000
